version: "3.9"
services:
  api:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG}
    pull_policy: always
    container_name: runova-backend
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
