version: "3.9"
services:
  api:
    build: .
    container_name: runova-backend
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: ["npm","run","start:dev"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
