version: "3.9"

services:
  api:
    build: .
    container_name: runova-backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
