name: Deploy to EC2

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/runova

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (using GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image to GHCR (linux/amd64)
        run: |
          TAG=${{ github.sha }}
          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE:$TAG \
            -t $IMAGE:latest \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        shell: bash
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Send env file
        shell: bash
        env:
          HOST: ${{ secrets.EC2_HOST }}
          PORT: ${{ secrets.EC2_PORT }}
          USER: ${{ secrets.EC2_USERNAME }}
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        run: |
          set -euo pipefail
          echo "$ENV_PRODUCTION" > .env.production
          ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -p "$PORT" "$USER@$HOST" 'mkdir -p ~/runova'
          scp -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -P "$PORT" .env.production "$USER@$HOST:/home/$USER/runova/.env.production"

      - name: Pull & Restart (pull image from GHCR and run)
        shell: bash
        env:
          HOST: ${{ secrets.EC2_HOST }}
          PORT: ${{ secrets.EC2_PORT }}
          USER: ${{ secrets.EC2_USERNAME }}
          IMAGE: ghcr.io/${{ github.repository_owner }}/runova
          TAG: ${{ github.sha }}
          GHCR_USER: ${{ secrets.EC2_GHCR_USER }}
          GHCR_PAT: ${{ secrets.EC2_GHCR_PAT }}
        run: |
          ssh -i key.pem \
              -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -o ServerAliveInterval=30 -o ServerAliveCountMax=120 \
              -p "$PORT" "$USER@$HOST" \
              IMAGE="$IMAGE" TAG="$TAG" GHCR_USER="${GHCR_USER:-}" GHCR_PAT="${GHCR_PAT:-}" bash -s <<'EOSSH'
            set -euo pipefail
            cd ~/runova

            test -f /etc/runova/certs/global-bundle.pem

            if [ -n "${GHCR_PAT}" ] && [ -n "${GHCR_USER}" ]; then
              echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin
            fi

            echo "[+] Pull image"
            docker pull "${IMAGE}:${TAG}"

            echo "[+] Ensure docker network"
            docker network create runova-net || true

            echo "[+] Stop previous containers"
            docker stop runova || true
            docker rm   runova || true
            docker stop runova-redis || true
            docker rm   runova-redis || true

            echo "[+] Run redis"
            docker run -d --name runova-redis --restart=always \
              --network runova-net \
              -e REDIS_URL=redis://runova-redis:6379/0 \
              -v /var/lib/runova/redis:/data \
              redis:7-alpine redis-server --appendonly yes

            echo "[+] Run API (with SSL CA volume)"
            docker run -d --name runova --restart=always \
              --env-file .env.production \
              --network runova-net \
              -e REDIS_HOST=runova-redis \
              -e REDIS_PORT=6379 \
              -v /etc/runova/certs/global-bundle.pem:/app/certs/global-bundle.pem:ro \
              -p 3000:3000 \
              "${IMAGE}:${TAG}"

            echo "[+] Verify volumes"
            docker exec runova sh -lc 'ls -l /app/certs && head -n2 /app/certs/global-bundle.pem'

            echo "[+] Deployed ${IMAGE}:${TAG}"
          EOSSH
