name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH port reachability
        run: |
          set -euxo pipefail
          HOST="${{ secrets.EC2_HOST }}"
          PORT="${{ secrets.EC2_PORT }}"
          timeout 3 bash -c "</dev/tcp/${HOST}/${PORT}" && echo "Port open" || (echo "Port closed"; exit 1)

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          command_timeout: 45m
          script: |
            set -euxo pipefail
            BRANCH="${{ github.ref_name }}"
            REPO_DIR=/home/${{ secrets.EC2_USERNAME }}/server

            if [ ! -d "$REPO_DIR/.git" ]; then
              mkdir -p "$REPO_DIR"
              git clone https://github.com/${{ github.repository }}.git "$REPO_DIR"
            fi

            cd "$REPO_DIR"
            git fetch --all --prune
            git checkout "$BRANCH"
            git reset --hard "origin/$BRANCH"

            # 환경파일 생성/갱신
            cat > .env.production <<'EOF'
            ${{ secrets.ENV_PRODUCTION }}
            EOF

            # 배포
            docker compose down --remove-orphans || true
            docker pull node:22-alpine || true
            docker pull redis:7-alpine || true
            docker compose --env-file .env.production build --pull --no-cache
            docker compose --env-file .env.production up -d --force-recreate

            docker compose ps
            docker compose logs runova-backend --since=2m || true
