name: Deploy to EC2 (no registry)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 레지스트리 푸시 대신, 런너에서 이미지 생성 → tar 파일로 저장
      - name: Build Docker image to local docker format
        run: |
          # 이미지 태그(브랜치별로 구분, 기본은 SHA)
          IMAGE_TAG=${{ github.sha }}
          # linux/amd64로 고정 (EC2 인스턴스 아키텍처에 맞춰 필요 시 변경)
          docker buildx build \
            --platform linux/amd64 \
            -t runova-backend:${IMAGE_TAG} \
            --output type=docker \
            .

      - name: Save image as tar
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker save runova-backend:${IMAGE_TAG} -o runova-backend-${IMAGE_TAG}.tar
          ls -lh runova-backend-${IMAGE_TAG}.tar

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            set -euxo pipefail
            cd ~/deploy/runova

            # .env 파일 생성 (Secrets에 전체 내용을 저장해둠)
            cat > .env.production <<'EOF'
            ${{ secrets.ENV_PRODUCTION }}
            EOF

            IMAGE_TAG=${{ github.sha }}
            IMAGE_NAME=runova-backend
            TAR_FILE=${IMAGE_NAME}-${IMAGE_TAG}.tar

            # tar 존재 확인
            ls -lah "${TAR_FILE}"

            # 이미지 로드
            docker load -i "${TAR_FILE}"

            # 기존 컨테이너 정리
            docker stop "${IMAGE_NAME}" || true
            docker rm "${IMAGE_NAME}" || true

            # 새 컨테이너 실행
            docker run -d \
              --name "${IMAGE_NAME}" \
              --restart unless-stopped \
              -p 127.0.0.1:3000:3000 \
              --env-file .env.production \
              ${IMAGE_NAME}:${IMAGE_TAG}

            # 정리
            docker image prune -f || true

            # 상태 점검
            docker ps
