name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          PORT: ${{ secrets.EC2_PORT }}
          USER: ${{ secrets.EC2_USERNAME }}
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$ENV_PRODUCTION" > .env.production

          scp -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $PORT .env.production $USER@$HOST:/home/$USER/runova/.env.production

          scp -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $PORT -r . $USER@$HOST:/home/$USER/runova

          ssh -i key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $PORT $USER@$HOST << 'EOF'
            cd ~/runova
            echo "[+] Building image"
            docker build -t runova-app .

            echo "[+] Stopping existing container"
            docker stop runova || true && docker rm runova || true

            echo "[+] Starting new container"
            docker run -d --name runova --restart=always --env-file .env.production -p 3000:3000 runova-app
          EOF
